# This workflow will build a .NET project and create a GitHub Release
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o output -r win-x64

    - name: Create ZIP Archive
      run: zip -r release.zip output/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-artifact
        path: release.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: release-artifact
        path: .

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
